const rooms = [
  { id: 'DM-204', name: 'Garden Terrace Suite', type: 'Suite', guests: 3, price: 185, status: 'Available', tone: 'green' },
  { id: 'DM-118', name: 'Dawn King Room', type: 'King room', guests: 2, price: 120, status: 'Available', tone: 'green' },
  { id: 'DM-307', name: 'Skyline Twin Room', type: 'Twin room', guests: 2, price: 145, status: 'Cleaning', tone: 'amber' },
];
const bookings = [
  { guest: 'Marta Tesfaye', room: 'DM-204', dates: 'Aug 28 - Sep 01', total: '$740', status: 'Confirmed', tone: 'green' },
  { guest: 'Daniel Bekele', room: 'DM-118', dates: 'Aug 26 - Aug 29', total: '$360', status: 'Checked in', tone: 'amber' },
  { guest: 'Liya Abebe', room: 'DM-307', dates: 'Aug 25 - Aug 27', total: '$290', status: 'Pending', tone: 'amber' },
];
let activeView = 'Overview';
let role = 'Manager';
let modal = '';
let query = '';

const navByRole = {
  Manager: ['Overview', 'Reservations', 'Reports', 'AI Insights'],
  Receptionist: ['Overview', 'Reservations', 'Check-in / out', 'Rooms', 'Food orders'],
  Admin: ['Overview', 'Users', 'Menu management', 'Rooms', 'Reports'],
  Guest: ['Find a room', 'My bookings', 'Restaurant menu', 'My profile'],
};
const icons = { Overview: '◫', Reservations: '▤', Reports: '◒', 'AI Insights': '✦', 'Check-in / out': '⇥', Rooms: '⌂', 'Food orders': '♨', Users: '♙', 'Menu management': '☷', 'Find a room': '⌕', 'My bookings': '▣', 'Restaurant menu': '♨', 'My profile': '○' };

function button(label, cls = 'btn-ghost', action = '') { return `<button class="btn ${cls}" data-action="${action || label}">${label}</button>`; }
function stat(value, label) { return `<div class="stat"><small>${label}</small><strong>${value}</strong></div>`; }
function status(text, tone) { return `<span class="status ${tone}">${text}</span>`; }
function shell(content) {
  const nav = navByRole[role].map(item => `<button class="${activeView === item ? 'active' : ''}" data-action="${item}">${icons[item] || '•'} <span>${item}</span></button>`).join('');
  return `<div class="shell"><aside class="sidebar"><div class="brand">Dream More<small>Hotel management</small></div><div class="nav-label">Workspace</div><nav class="nav">${nav}</nav><div class="profile">${role === 'Guest' ? 'Marta Tesfaye' : 'Amanuel Haile'}<span>${role} account</span></div></aside><main class="main"><header class="topbar"><div class="crumb">Dream More Hotel <b>/</b> ${activeView}</div><div class="top-actions"><button class="icon-button" title="Notifications">♧</button><div class="avatar">${role[0]}</div><select id="role-select" aria-label="Preview role"><option ${role === 'Manager' ? 'selected' : ''}>Manager</option><option ${role === 'Receptionist' ? 'selected' : ''}>Receptionist</option><option ${role === 'Admin' ? 'selected' : ''}>Admin</option><option ${role === 'Guest' ? 'selected' : ''}>Guest</option></select></div></header><section class="content">${content}</section></main></div>`;
}
function managerOverview() {
  return `<div class="hero"><div><div class="eyebrow">Monday, August 24, 2026</div><h1>Good morning, Amanuel.</h1><p class="lede">A clear view of today's hotel operations, from the front desk to the last room.</p>${button('View reports', 'btn-primary', 'Reports')}</div><div class="hero-panel"><div class="eyebrow">Occupancy today</div><h2 style="color:white;margin:8px 0 4px">78.4%</h2><p style="color:#b5d6ce;margin:0">112 of 143 rooms occupied</p></div></div><div class="grid grid-4 stats">${stat('143','Total rooms')}${stat('112','Occupied today')}${stat('$8,420','Revenue this month')}${stat('14','Open reservations')}</div><div class="section-head"><h2>Today's reservations</h2>${button('View all', 'btn-ghost', 'Reservations')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>Guest</th><th>Room</th><th>Stay</th><th>Total</th><th>Status</th></tr></thead><tbody>${bookings.map(b => `<tr><td><b>${b.guest}</b></td><td>${b.room}</td><td>${b.dates}</td><td>${b.total}</td><td>${status(b.status,b.tone)}</td></tr>`).join('')}</tbody></table></div>`;
}
function guestOverview() { return `<div class="eyebrow">Welcome back</div><h1>Your stay, thoughtfully managed.</h1><p class="lede">Find a quiet room, keep track of upcoming stays, and order something good from the restaurant.</p><div class="grid grid-3 stats">${stat('1','Upcoming stay')}${stat('2','Past bookings')}${stat('$0','Open balance')}</div><div class="grid grid-3"><div class="card"><div class="eyebrow">Next stay</div><h3 style="margin-top:14px">Garden Terrace Suite</h3><p class="lede">Aug 28 - Sep 01 · 4 nights</p>${button('View booking','btn-teal','My bookings')}</div><div class="card"><div class="eyebrow">Make it yours</div><h3 style="margin-top:14px">Find another room</h3><p class="lede">Explore the rooms and choose the right pace for your next visit.</p>${button('Browse rooms','btn-primary','Find a room')}</div><div class="card"><div class="eyebrow">From the kitchen</div><h3 style="margin-top:14px">Order from the menu</h3><p class="lede">Fresh food, delivered to your room when you are ready.</p>${button('See menu','btn-ghost','Restaurant menu')}</div></div>`; }
function receptionOverview() { return `<div class="eyebrow">Front desk · Monday, August 24</div><h1>Today's desk.</h1><p class="lede">Keep arrivals moving, rooms turning over, and every guest feeling expected.</p><div class="grid grid-4 stats">${stat('18','Arrivals today')}${stat('11','Departures')}${stat('7','Rooms to clean')}${stat('3','Open food orders')}</div><div class="section-head"><h2>Front desk queue</h2>${button('Manage reservations','btn-teal','Reservations')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>Guest</th><th>Room</th><th>Arrival</th><th>Status</th><th>Action</th></tr></thead><tbody>${bookings.map(b=>`<tr><td><b>${b.guest}</b></td><td>${b.room}</td><td>${b.dates.split(' - ')[0]}</td><td>${status(b.status,b.tone)}</td><td>${button('Open','btn-ghost','Open '+b.guest)}</td></tr>`).join('')}</tbody></table></div>`; }
function adminOverview() { return `<div class="eyebrow">Administration</div><h1>System overview.</h1><p class="lede">Keep users, rooms, menus, and access policies in good order.</p><div class="grid grid-4 stats">${stat('24','Active users')}${stat('143','Room records')}${stat('36','Menu items')}${stat('99.9%','Service health')}</div><div class="grid grid-3"><div class="card"><div class="eyebrow">Access</div><h3 style="margin-top:14px">Manage users</h3><p class="lede">Assign roles and review account activity.</p>${button('Open users','btn-teal','Users')}</div><div class="card"><div class="eyebrow">Restaurant</div><h3 style="margin-top:14px">Menu management</h3><p class="lede">Keep dishes, prices, and availability current.</p>${button('Open menu','btn-primary','Menu management')}</div><div class="card"><div class="eyebrow">Audit</div><h3 style="margin-top:14px">Recent activity</h3><p class="lede">No unusual sign-in or data-change activity detected.</p>${button('View reports','btn-ghost','Reports')}</div></div>`; }
function roomsView() {
  const filtered = rooms.filter(r => `${r.name} ${r.type}`.toLowerCase().includes(query.toLowerCase()));
  return `<div class="eyebrow">Guest experience</div><h1>Find your room.</h1><p class="lede">Thoughtful spaces, ready when you are. Search availability for your next stay at Dream More.</p><div class="card" style="margin:28px 0"><div class="form-grid"><div class="field"><label>Check-in</label><input type="date" value="2026-08-28"></div><div class="field"><label>Check-out</label><input type="date" value="2026-09-01"></div><div class="field"><label>Guests</label><select><option>2 guests</option><option>3 guests</option><option>4 guests</option></select></div><div style="align-self:end">${button('Search rooms','btn-teal','Search rooms')}</div></div></div><div class="section-head"><h2>Available rooms</h2><input class="search" id="room-search" placeholder="Search by room type..." value="${query}"></div><div class="grid grid-3">${filtered.length ? filtered.map(r => `<article class="card room"><div class="room-image"><span>${r.status}</span></div><div class="room-body"><div class="eyebrow">${r.type}</div><h3>${r.name}</h3><div class="room-meta"><span>♧ ${r.guests} guests</span><span>☼ Garden view</span></div><div class="bar"><span class="price">$${r.price} <small>/ night</small></span>${button('Reserve','btn-primary','Reserve '+r.id)}</div></div></article>`).join('') : '<div class="card empty">No rooms match that search.</div>'}</div>`;
}
function reservationsView() { return `<div class="bar"><div><div class="eyebrow">Operations</div><h1>Reservations</h1></div>${button('New reservation','btn-teal','New reservation')}</div><div class="notice">Availability is synchronized with room status. Payment credentials remain protected on the server.</div><div class="card"><div class="bar"><input class="search" id="booking-search" placeholder="Search guest or room..."><select id="booking-filter"><option>All statuses</option><option>Confirmed</option><option>Pending</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Guest</th><th>Room</th><th>Stay</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>${bookings.map(b=>`<tr><td><b>${b.guest}</b></td><td>${b.room}</td><td>${b.dates}</td><td>${b.total}</td><td>${status(b.status,b.tone)}</td><td>${button('Details','btn-ghost','Details '+b.guest)}</td></tr>`).join('')}</tbody></table></div></div>`; }
function reportsView() { return `<div class="eyebrow">Management intelligence</div><h1>Reports & insights.</h1><p class="lede">Understand performance at a glance, with live operational metrics ready for the next decision.</p><div class="grid grid-3 stats">${stat('$28,640','Revenue this month')}${stat('82.1%','Average occupancy')}${stat('$64.20','Average food order')}</div><div class="grid grid-3"><div class="card"><div class="eyebrow">Occupancy</div><h3 style="margin-top:14px">Weekly room utilization</h3><div style="height:130px;background:linear-gradient(165deg,transparent 45%,#dceee9 46%,#0d766c 48%,#dceee9 50%,transparent 51%);border-bottom:1px solid var(--line)"></div></div><div class="card"><div class="eyebrow">Revenue mix</div><h3 style="margin-top:14px">Rooms lead the month</h3><p class="lede">Room revenue 72% · Food sales 18% · Other 10%</p>${button('Export report','btn-ghost','Export report')}</div><div class="card"><div class="eyebrow">AI summary</div><h3 style="margin-top:14px">A stronger weekend ahead</h3><p class="lede">Occupancy is trending 8% above last month. Consider opening the rooftop menu earlier on Friday.</p>${button('Read AI insights','btn-primary','AI Insights')}</div></div>`; }
function genericView() { return `<div class="eyebrow">${role} workspace</div><h1>${activeView}</h1><p class="lede">This operational view is ready for live Node/Express API wiring. Use the role switcher to review the access boundaries defined in the SRS.</p><div class="card empty">No live API connection configured. The frontend service boundary is ready for PostgreSQL-backed data.</div>`; }
function render() { let view = activeView === 'Find a room' ? roomsView() : activeView === 'Reservations' ? reservationsView() : activeView === 'Reports' ? reportsView() : activeView === 'Overview' ? (role === 'Guest' ? guestOverview() : role === 'Receptionist' ? receptionOverview() : role === 'Admin' ? adminOverview() : managerOverview()) : genericView(); document.getElementById('app').innerHTML = shell(view) + (modal ? `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><div class="eyebrow">${modal.startsWith('Reserve') ? 'Reservation request' : 'Demo action'}</div><h2>${modal}</h2></div><button class="close" data-action="close">×</button></div><p class="lede">This interaction is connected to the UI state. Connect it to the relevant API endpoint when the Node/Express service is available.</p>${button('Continue','btn-teal','close')}</div></div>` : ''); }
document.addEventListener('click', e => { const action = e.target.closest('[data-action]')?.dataset.action; if (!action) return; if (action === 'close') modal = ''; else if (navByRole[role].includes(action)) { activeView = action; query = ''; } else modal = action; render(); });
document.addEventListener('change', e => { if (e.target.id === 'role-select') { role = e.target.value; activeView = navByRole[role][0]; render(); } });
document.addEventListener('input', e => { if (e.target.id === 'room-search') { query = e.target.value; render(); document.getElementById('room-search')?.focus(); } });
render();
